# Generated by Django 3.1.13 on 2021-11-17 15:32

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vycinity.models.firewall_models
import vycinity.models.network_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractOwnedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('state', models.CharField(choices=[('prepared', 'prepared'), ('live', 'live'), ('outdated', 'outdated'), ('deleted', 'deleted')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('parent_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ManagedInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipv4_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('ipv6_address', models.GenericIPAddressField(null=True, protocol='IPv6')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('loopback', models.GenericIPAddressField(unique=True, unpack_ipv4=True)),
                ('deploy', models.BooleanField(default=False)),
                ('managed_interface_context', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RouterConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.router')),
            ],
        ),
        migrations.CreateModel(
            name='StaticConfigSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.JSONField()),
                ('description', models.TextField(null=True)),
                ('absolute', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AddressObject',
            fields=[
                ('abstractownedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.abstractownedobject')),
                ('public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.abstractownedobject',),
        ),
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('abstractownedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.abstractownedobject')),
                ('public', models.BooleanField(default=False)),
                ('stateful', models.BooleanField()),
                ('name', models.CharField(max_length=64)),
                ('default_action_into', models.CharField(choices=[('accept', 'accept'), ('drop', 'drop'), ('reject', 'reject')], max_length=16)),
                ('default_action_from', models.CharField(choices=[('accept', 'accept'), ('drop', 'drop'), ('reject', 'reject')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.abstractownedobject',),
        ),
        migrations.CreateModel(
            name='ManagedVRRPInterface',
            fields=[
                ('managedinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.managedinterface')),
                ('ipv4_service_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('ipv6_service_address', models.GenericIPAddressField(null=True, protocol='IPv6')),
                ('priority', models.IntegerField()),
                ('vrid', models.IntegerField()),
            ],
            bases=('vycinity.managedinterface',),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('abstractownedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.abstractownedobject')),
                ('public', models.BooleanField(default=False)),
                ('ipv4_network_address', models.GenericIPAddressField(null=True, protocol='IPv4', unique=True)),
                ('ipv4_network_bits', models.IntegerField(null=True, validators=[vycinity.models.network_models.validate_ipv4_network_bits])),
                ('ipv6_network_address', models.GenericIPAddressField(null=True, protocol='IPv6', unique=True)),
                ('ipv6_network_bits', models.IntegerField(null=True, validators=[vycinity.models.network_models.validate_ipv6_network_bits])),
                ('layer2_network_id', models.IntegerField(validators=[vycinity.models.network_models.validate_layer2_id])),
                ('name', models.CharField(max_length=64)),
                ('vrrp_password', models.CharField(max_length=8, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.abstractownedobject',),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('abstractownedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.abstractownedobject')),
                ('priority', models.IntegerField(validators=[vycinity.models.firewall_models.validate_priority_rule])),
                ('comment', models.TextField(null=True)),
                ('disable', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.abstractownedobject',),
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('abstractownedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.abstractownedobject')),
                ('public', models.BooleanField(default=False)),
                ('priority', models.IntegerField(validators=[vycinity.models.firewall_models.validate_priority_rule])),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.abstractownedobject',),
        ),
        migrations.CreateModel(
            name='ServiceObject',
            fields=[
                ('abstractownedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.abstractownedobject')),
                ('public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.abstractownedobject',),
        ),
        migrations.CreateModel(
            name='Vyos13Router',
            fields=[
                ('router_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.router')),
                ('token', models.CharField(max_length=256)),
                ('fingerprint', models.CharField(max_length=256)),
            ],
            bases=('vycinity.router',),
        ),
        migrations.CreateModel(
            name='Vyos13RouterConfig',
            fields=[
                ('routerconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.routerconfig')),
                ('config', models.JSONField()),
            ],
            bases=('vycinity.routerconfig',),
        ),
        migrations.CreateModel(
            name='Vyos13StaticConfigSection',
            fields=[
                ('staticconfigsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.staticconfigsection')),
                ('content', models.JSONField()),
            ],
            bases=('vycinity.staticconfigsection',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=64, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer')),
            ],
        ),
        migrations.AddField(
            model_name='managedinterface',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.router'),
        ),
        migrations.CreateModel(
            name='LocalUserAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.user')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('change', models.JSONField()),
                ('state', models.CharField(choices=[('preparation', 'preparation'), ('ready', 'ready to run'), ('running', 'running'), ('failed', 'failed'), ('succeed', 'succeed')], max_length=32)),
                ('errors', models.TextField(null=True)),
                ('configs', models.ManyToManyField(to='vycinity.RouterConfig')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(editable=False, max_length=64)),
                ('user_name', models.CharField(editable=False, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('applied', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vycinity.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vycinity.user')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'created'), ('modified', 'modified'), ('deleted', 'deleted')], max_length=8)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='vycinity.changeset')),
                ('dependencies', models.ManyToManyField(related_name='dependents', to='vycinity.Change')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change', to='vycinity.abstractownedobject')),
                ('pre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vycinity.abstractownedobject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='abstractownedobject',
            constraint=models.UniqueConstraint(condition=models.Q(state='live'), fields=('uuid', 'state'), name='vycinity_max_one_abstractownedobject_live'),
        ),
        migrations.CreateModel(
            name='CIDRAddressObject',
            fields=[
                ('addressobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.addressobject')),
                ('ipv6_network_address', models.GenericIPAddressField(null=True, protocol='IPv6')),
                ('ipv6_network_bits', models.IntegerField(null=True, validators=[vycinity.models.network_models.validate_ipv6_network_bits])),
                ('ipv4_network_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('ipv4_network_bits', models.IntegerField(null=True, validators=[vycinity.models.network_models.validate_ipv4_network_bits])),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.addressobject',),
        ),
        migrations.CreateModel(
            name='CustomRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.rule')),
                ('ip_version', models.IntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')])),
                ('direction', models.CharField(choices=[('into', 'into'), ('from', 'from')], max_length=4)),
                ('rule_definition', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.rule',),
        ),
        migrations.CreateModel(
            name='HostAddressObject',
            fields=[
                ('addressobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.addressobject')),
                ('ipv6_address', models.GenericIPAddressField(null=True, protocol='IPv6')),
                ('ipv4_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.addressobject',),
        ),
        migrations.CreateModel(
            name='RangeServiceObject',
            fields=[
                ('serviceobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.serviceobject')),
                ('protocol', models.CharField(max_length=16)),
                ('start_port', models.IntegerField(validators=[vycinity.models.firewall_models.validate_port_simpleserviceobject])),
                ('end_port', models.IntegerField(validators=[vycinity.models.firewall_models.validate_port_simpleserviceobject])),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.serviceobject',),
        ),
        migrations.CreateModel(
            name='SimpleServiceObject',
            fields=[
                ('serviceobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.serviceobject')),
                ('protocol', models.CharField(max_length=16)),
                ('port', models.IntegerField(validators=[vycinity.models.firewall_models.validate_port_simpleserviceobject])),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.serviceobject',),
        ),
        migrations.AddField(
            model_name='vyos13router',
            name='active_static_configs',
            field=models.ManyToManyField(blank=True, to='vycinity.Vyos13StaticConfigSection'),
        ),
        migrations.AddField(
            model_name='serviceobject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer'),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='firewalls',
            field=models.ManyToManyField(to='vycinity.Firewall'),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer'),
        ),
        migrations.AddField(
            model_name='rule',
            name='related_ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.ruleset'),
        ),
        migrations.AddField(
            model_name='network',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer'),
        ),
        migrations.AddField(
            model_name='managedinterface',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.network'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='related_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vycinity.network'),
        ),
        migrations.AddField(
            model_name='addressobject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer'),
        ),
        migrations.CreateModel(
            name='NetworkAddressObject',
            fields=[
                ('addressobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.addressobject')),
                ('related_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.network')),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.addressobject',),
        ),
        migrations.CreateModel(
            name='ListServiceObject',
            fields=[
                ('serviceobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.serviceobject')),
                ('elements', models.ManyToManyField(related_name='_listserviceobject_elements_+', to='vycinity.ServiceObject')),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.serviceobject',),
        ),
        migrations.CreateModel(
            name='ListAddressObject',
            fields=[
                ('addressobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.addressobject')),
                ('elements', models.ManyToManyField(related_name='_listaddressobject_elements_+', to='vycinity.AddressObject')),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.addressobject',),
        ),
        migrations.CreateModel(
            name='BasicRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.rule')),
                ('action', models.CharField(choices=[('accept', 'accept'), ('drop', 'drop'), ('reject', 'reject')], max_length=16)),
                ('log', models.BooleanField()),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='vycinity.addressobject')),
                ('destination_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='vycinity.serviceobject')),
                ('source_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='vycinity.addressobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('vycinity.rule',),
        ),
    ]
