# Generated by Django 3.1.5 on 2021-01-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticconfigsection',
            name='content',
        ),
        migrations.AddField(
            model_name='staticconfigsection',
            name='active_routers',
            field=models.ManyToManyField(to='vycinity.Router'),
        ),
        migrations.AddField(
            model_name='vyos13router',
            name='fingerprint',
            field=models.CharField(default='-', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='router',
            name='loopback',
            field=models.GenericIPAddressField(unique=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='type',
            field=models.CharField(choices=[('vyos13', 'VyOS 1.3+')], max_length=64),
        ),
        migrations.AlterField(
            model_name='staticconfigsection',
            name='context',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='staticconfigsection',
            name='type',
            field=models.CharField(choices=[('vyos13', 'VyOS 1.3+')], max_length=64),
        ),
        migrations.CreateModel(
            name='Vyos13StaticConfigSection',
            fields=[
                ('staticconfigsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.staticconfigsection')),
                ('content', models.JSONField()),
            ],
            bases=('vycinity.staticconfigsection',),
        ),
    ]
