# Generated by Django 3.1.13 on 2022-01-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change', to='vycinity.abstractownedobject'),
        ),
    ]
