# Generated by Django 3.1.5 on 2021-01-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0002_auto_20210127_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='type',
        ),
        migrations.RemoveField(
            model_name='staticconfigsection',
            name='type',
        ),
    ]
