# Generated by Django 3.1.13 on 2022-01-24 08:39, modified

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vycinity', '0002_auto_20220104_1358'),
    ]

    def forward_set_ctypes(apps, schema_editor):
        # Setting the ctype as required by polymorphic (https://django-polymorphic.readthedocs.io/en/stable/migrating.html)
        ContentType = apps.get_model('contenttypes', 'ContentType')
        for current_app_model in ['AbstractOwnedObject', 'Change', 'ChangeSet', 'Customer', 'Deployment', 'LocalUserAuth', 'ManagedInterface', 'Router', 'RouterConfig', 'StaticConfigSection', 'User']:
            current_model = apps.get_model('vycinity', current_app_model)
            new_ctype = ContentType.objects.get_for_model(current_model)
            current_model.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ctype)
        

    operations = [
        migrations.AddField(
            model_name='abstractownedobject',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.abstractownedobject_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='change',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.change_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='changeset',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.changeset_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.customer_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.deployment_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='localuserauth',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.localuserauth_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='managedinterface',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.managedinterface_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='router',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.router_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.routerconfig_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='staticconfigsection',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.staticconfigsection_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='user',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.user_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forward_set_ctypes, migrations.RunPython.noop),
    ]
