# Generated by Django 3.1.5 on 2021-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0003_auto_20210127_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticconfigsection',
            name='active_routers',
        ),
        migrations.AddField(
            model_name='staticconfigsection',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vyos13router',
            name='active_static_configs',
            field=models.ManyToManyField(to='vycinity.Vyos13StaticConfigSection'),
        ),
    ]
