# Generated by Django 3.2.13 on 2022-10-26 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vycinity', '0003_auto_20220124_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRouterConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retrieved', models.DateTimeField(null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vycinity.liverouterconfig_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='change',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='changeset',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='deployment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='localuserauth',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='managedinterface',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='managedvrrpinterface',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='router',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='routerconfig',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='staticconfigsection',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='vyos13router',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='vyos13routerconfig',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='vyos13staticconfigsection',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='related_ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vycinity.ruleset'),
        ),
        migrations.CreateModel(
            name='Vyos13LiveRouterConfig',
            fields=[
                ('liverouterconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.liverouterconfig')),
                ('config', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vycinity.liverouterconfig',),
        ),
        migrations.AddField(
            model_name='liverouterconfig',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.router'),
        ),
    ]
