# Generated by Django 3.1.5 on 2021-01-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0004_auto_20210128_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('change', models.JSONField()),
                ('state', models.CharField(choices=[('running', 'running'), ('failed', 'failed'), ('succeed', 'succeed')], max_length=32)),
                ('errors', models.TextField(null=True)),
                ('routers', models.ManyToManyField(to='vycinity.Router')),
            ],
        ),
    ]
