# Generated by Django 3.2.16 on 2023-02-06 10:55

from django.db import migrations, models
import vycinity.models.basic_models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0004_auto_20221026_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='ipv4_network_address',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='network',
            name='ipv6_network_address',
            field=models.GenericIPAddressField(null=True, protocol='IPv6'),
        ),
        migrations.AlterField(
            model_name='vyos13staticconfigsection',
            name='content',
            field=models.JSONField(validators=[vycinity.models.basic_models.validate_is_object]),
        ),
    ]
