# Generated by Django 3.2.16 on 2023-06-06 09:43

from django.db import migrations, models
import django.db.models.deletion
import vycinity.models.network_models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0005_auto_20230206_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='managedinterface',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.network', validators=[vycinity.models.network_models.validate_live_object]),
        ),
    ]
