# Generated by Django 3.1.5 on 2021-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0006_auto_20210128_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='state',
            field=models.CharField(choices=[('preparation', 'preparation'), ('ready', 'ready to run'), ('running', 'running'), ('failed', 'failed'), ('succeed', 'succeed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='vyos13router',
            name='active_static_configs',
            field=models.ManyToManyField(blank=True, to='vycinity.Vyos13StaticConfigSection'),
        ),
    ]
