# Generated by Django 3.1.5 on 2021-02-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0007_auto_20210128_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='routers',
        ),
        migrations.AddField(
            model_name='router',
            name='deploy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='router',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staticconfigsection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Vyos13RouterConfig',
            fields=[
                ('routerconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.routerconfig')),
                ('config', models.JSONField()),
            ],
            bases=('vycinity.routerconfig',),
        ),
        migrations.AddField(
            model_name='routerconfig',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.router'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='configs',
            field=models.ManyToManyField(to='vycinity.RouterConfig'),
        ),
    ]
