# Generated by Django 3.1.7 on 2021-03-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0008_auto_20210210_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('parent_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer')),
            ],
        ),
    ]
