# Generated by Django 3.1.7 on 2021-03-11 08:25

from django.db import migrations, models
import django.db.models.deletion
import vycinity.models.network_models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0009_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedInterface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipv4_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('ipv6_address', models.GenericIPAddressField(null=True, protocol='IPv6')),
            ],
        ),
        migrations.CreateModel(
            name='ManagedVRRPInterface',
            fields=[
                ('managedinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vycinity.managedinterface')),
                ('ipv4_service_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('ipv6_service_address', models.GenericIPAddressField(null=True, protocol='IPv6')),
                ('priority', models.IntegerField()),
                ('vrid', models.IntegerField()),
            ],
            bases=('vycinity.managedinterface',),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipv4_network_address', models.GenericIPAddressField(null=True, protocol='IPv4', unique=True)),
                ('ipv4_network_bits', models.IntegerField(null=True, validators=[vycinity.models.network_models.validate_ipv4_network_bits])),
                ('ipv6_network_address', models.GenericIPAddressField(null=True, protocol='IPv6', unique=True)),
                ('ipv6_network_bits', models.IntegerField(null=True, validators=[vycinity.models.network_models.validate_ipv6_network_bits])),
                ('layer2_network_id', models.IntegerField(validators=[vycinity.models.network_models.validate_layer2_id])),
                ('name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer')),
            ],
        ),
        migrations.AddField(
            model_name='managedinterface',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.network'),
        ),
        migrations.AddField(
            model_name='managedinterface',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.router'),
        ),
    ]
