# Generated by Django 3.1.7 on 2021-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0010_auto_20210311_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='managed_interface_context',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
