# Generated by Django 3.1.7 on 2021-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0011_router_managed_interface_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='vrrp_password',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
