# Generated by Django 3.1.7 on 2021-05-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0013_auto_20210330_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaddressobject',
            name='elements',
            field=models.ManyToManyField(related_name='_listaddressobject_elements_+', to='vycinity.AddressObject'),
        ),
        migrations.AlterField(
            model_name='listserviceobject',
            name='elements',
            field=models.ManyToManyField(related_name='_listserviceobject_elements_+', to='vycinity.ServiceObject'),
        ),
        migrations.AlterField(
            model_name='standardrule',
            name='destination_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='vycinity.addressobject'),
        ),
        migrations.AlterField(
            model_name='standardrule',
            name='destination_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='vycinity.serviceobject'),
        ),
        migrations.AlterField(
            model_name='standardrule',
            name='source_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='vycinity.addressobject'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=64, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LocalUserAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.user')),
            ],
        ),
    ]
