# Generated by Django 3.1.7 on 2021-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0014_auto_20210527_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewall',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
