# Generated by Django 3.1.7 on 2021-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0015_auto_20210527_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceobject',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
