# Generated by Django 3.1.7 on 2021-06-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0016_auto_20210608_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewall',
            old_name='default_action',
            new_name='default_action_from',
        ),
        migrations.AddField(
            model_name='customrule',
            name='direction',
            field=models.CharField(choices=[('into', 'into'), ('from', 'from')], default='into', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firewall',
            name='default_action_into',
            field=models.CharField(choices=[('accept', 'accept'), ('drop', 'drop'), ('reject', 'reject')], default='drop', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firewall',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vycinity.network'),
        ),
    ]
