# Generated by Django 3.1.7 on 2021-07-05 11:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0018_auto_20210702_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(editable=False, max_length=64)),
                ('user_name', models.CharField(editable=False, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('applied', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vycinity.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vycinity.user')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=255)),
                ('pre', models.JSONField()),
                ('post', models.JSONField()),
                ('new_uuid', models.UUIDField(null=True)),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vycinity.changeset')),
            ],
        ),
    ]
