# Generated by Django 3.1.7 on 2021-07-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0019_change_changeset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandardRule',
            new_name='BasicRule',
        ),
        migrations.AlterField(
            model_name='change',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='vycinity.changeset'),
        ),
    ]
