# Generated by Django 3.1.13 on 2021-10-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0020_auto_20210714_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='post',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='pre',
            field=models.JSONField(null=True),
        ),
    ]
