# Generated by Django 3.1.13 on 2021-10-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vycinity', '0021_auto_20211008_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='dependencies',
            field=models.ManyToManyField(related_name='dependents', to='vycinity.Change'),
        ),
    ]
